/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_JNIMain */

#ifndef _Included_jni_JNIMain
#define _Included_jni_JNIMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNIMain
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JNIMain_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
